---
name: M3uPlayer
version: dev
slug: m3u_player
description: M3uPlayer Homeassistant
url: https://github.com/sdavides/m3u8-HLS-Homeassistant
codenotary: codenotary@frenck.dev
ingress: true
ingress_port: 0
ingress_stream: true
panel_icon: mdi:animation-play
init: false
homeassistant: 2023.3.0
arch:
  - aarch64
  - amd64
  - armv7
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_network: true
auth_api: true
uart: true
list_video_description:
  80/tcp: Web interface Nginx external port
map:
  - addon_config:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl
options:
  list_video: true
  url_m3u: ""
  searchInput: false
  channelSelect: true
  fileInput: false
  urlInput: false
  remoteUrlInput: false
schema:
  list_video: bool?
  url_m3u: str
  searchInput: bool?
  channelSelect: bool?
  fileInput: bool?
  urlInput: bool?
  remoteUrlInput: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?